
CREATE TABLE IF NOT EXISTS community (
    id INT AUTO_INCREMENT(100) PRIMARY KEY,
    name VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS household (
    ID INT AUTO_INCREMENT(100) PRIMARY KEY,
    NAME_OR_NUMBER VARCHAR(250),
    POSTCODE VARCHAR(250),
    COMMUNITY_ID INT
);

CREATE TABLE IF NOT EXISTS member (
    ID INT AUTO_INCREMENT(100) PRIMARY KEY,
    PREFERRED_NAME VARCHAR(250),
    HOUSEHOLD_ID INT,
    USER_ID VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS thing (
    id INT AUTO_INCREMENT(100) PRIMARY KEY,
    name VARCHAR(250),
    quantity VARCHAR(250),
    category VARCHAR(250),
    MEMBER_ID INT
);

ALTER TABLE household
    ADD FOREIGN KEY (COMMUNITY_ID)
    REFERENCES community(id);

ALTER TABLE member
    ADD FOREIGN KEY (HOUSEHOLD_ID)
    REFERENCES household(ID);

ALTER TABLE thing
    ADD FOREIGN KEY (MEMBER_ID)
    REFERENCES member(id);
